### ISSUE TITLE
Use commandline args for extra jars

### ISSUE THREAD

**Issue by wearpants** [davidmcclure/osp-pipeline#6]
Instead of downloading the jars as described in README, use commandline arguments to `spark-submit` like:

`                        '--packages','org.apache.hadoop:hadoop-aws:2.7.3',
                        '--packages','com.amazonaws:aws-java-sdk:1.7.4',
                        '--packages','com.databricks:spark-avro_2.10:3.1.0',
`

(this is what is done in the EMR scripts)

**Comment by davidmcclure** [comment]
These are now set in `spark-defauts.conf`.
